INSERT INTO filmes(id,filme) VALUES 
    (1,'Os Sete Samurais'),
    (2,'Bonnie e Clyde - Uma Rajada de Balas'),
    (3,'Cães de Aluguel'),
    (4,'Apertem os Cintos… O Piloto Sumiu'),
    (5,'O Labirinto do Fauno'),
    (6,'Doutor Jivago'),
    (7,'O Franco-Atirador'),
    (8,'Contatos Imediatos de Terceiro Grau'),
    (9,'Up - Altas Aventuras'),
    (10,'Rocky, um Lutador'),
    (11,'Amnésia'),
    (12,'Coração Valente'),
    (13,'Quem Quer Ser um Milionário?'),
    (14,'Senhor dos Anéis: O Retorno do Rei'),
    (15,'A Bela e a Fera'),
    (16,'Seven - Os Sete Crimes Capitais'),
    (17,'A Origem'),
    (18,'Duro de Matar'),
    (19,'Senhor dos Anéis: A Sociedade do Anel'),
    (20,'Amadeus'),
    (21,'Sindicato de Ladrões'),
    (22,'Wall-E'),
    (23,'12 Homens e uma Sentença'),
    (24,'Os Caça-Fantasmas'),
    (25,'O Segredo de Brokeback Mountain'),
    (26,'A Ponte do Rio Kwai'),
    (27,'Banzé no Oeste'),
    (28,'Todos os Homens do Presidente'),
    (29,'O Jovem Frankenstein'),
    (30,'Quase Famosos'),
    (31,'Um Corpo que Cai'),
    (32,'Gladiador'),
    (33,'Monty Python Em Busca do Cálice Sagrado'),
    (34,'Avatar'),
    (35,'O Rei Leão'),
    (36,'Touro Indomável'),
    (37,'Mary Poppins'),
    (38,'Feitiço do Tempo'),
    (39,'Intriga Internacional'),
    (40,'Amor, Sublime Amor'),
    (41,'O Fabuloso Destino de Amélie Poulain'),
    (42,'Thelma & Louise'),
    (43,'Crepúsculo dos Deuses'),
    (44,'Batman: O Cavaleiro das Trevas'),
    (45,'Brilho Eterno de uma Mente sem Lembranças'),
    (46,'Taxi Driver - Motorista de Táxi'),
    (47,'Butch Cassidy'),
    (48,'Gênio Indomável'),
    (49,'A Malvada'),
    (50,'O Grande Lebowski'),
    (51,'Jurassic Park: O Parque dos Dinossauros'),
    (52,'Janela Indiscreta'),
    (53,'Os Suspeitos'),
    (54,'Quanto Mais Quente Melhor'),
    (55,'O Resgate do Soldado Ryan'),
    (56,'Titanic'),
    (57,'Matrix'),
    (58,'Toy Story'),
    (59,'Alien, o Oitavo Passageiro'),
    (60,'Psicose'),
    (61,'Clube da Luta'),
    (62,'O Iluminado'),
    (63,'Harry e Sally - Feitos Um para o Outro'),
    (64,'Fantástico'),
    (65,'Curtindo a Vida Adoidado'),
    (66,'Laranja Mecânica'),
    (67,'Beleza Americana'),
    (68,'Fargo'),
    (69,'Star Wars: O Império Contra-Ataca'),
    (70,'A Princesa Prometida'),
    (71,'Um Estranho no Ninho'),
    (72,'Blade Runner, o Caçador de Andróides'),
    (73,'A Primeira Noite de um Homem'),
    (74,'Clube dos Cinco'),
    (75,'Cantando na Chuva'),
    (76,'A Noviça Rebelde'),
    (77,'Tubarão'),
    (78,'Lawrence da Arábia'),
    (79,'O Silêncio dos Inocentes'),
    (80,'Chinatown'),
    (81,'A Felicidade Não se Compra'),
    (82,'Os Bons Companheiros'),
    (83,'Noivo Neurótico, Noiva Nervosa'),
    (84,'Apocalypse Now'),
    (85,'O Sol é Para Todos'),
    (86,'o Vento Levou'),
    (87,'Forrest Gump: O Contador de Histórias'),
    (88,'Indiana Jones e os Caçadores da Arca Perdida'),
    (89,'De Volta Para o Futuro'),
    (90,'Star Wars: Uma Nova Esperança'),
    (91,'A Lista de Schindler'),
    (92,'2001: Uma Odisséia no Espaço'),
    (93,'ET - O Extraterrestre'),
    (94,'O Poderoso Chefão: Parte II'),
    (95,'Casablanca'),
    (96,'Pulp Fiction - Tempo de Violência'),
    (97,'Um Sonho de Liberdade'),
    (98,'Cidadão Kane'),
    (99,'O Mágico de Oz'),
    (100,'O Poderoso Chefão')
;
