INSERT INTO usuarios(id,usuario,sexo) VALUES
    (1,'Helena','F'),
    (2,'Miguel','M'),
    (3,'Alice','F'),
    (4,'Arthur','M'),
    (5,'Laura','F'),
    (6,'Heitor','M'),
    (7,'Manuela','F'),
    (8,'Bernardo','M'),
    (9,'Valentina','F'),
    (10,'Davi','M'),
    (11,'Sophia','F'),
    (12,'Théo','M'),
    (13,'Isabella','F'),
    (14,'Lorenzo','M'),
    (15,'Heloísa','F'),
    (16,'Gabriel','M'),
    (17,'Luiza','F'),
    (18,'Pedro','M'),
    (19,'Júlia','F'),
    (20,'Benjamin','M'),
    (21,'Lorena','F'),
    (22,'Matheus','M'),
    (23,'Lívia','F'),
    (24,'Lucas','M'),
    (25,'Maria Luiza','F'),
    (26,'Nicolas','M'),
    (27,'Cecília','F'),
    (28,'Joaquim','M'),
    (29,'Eloá','F'),
    (30,'Samuel','M'),
    (31,'Giovanna','F'),
    (32,'Henrique','M'),
    (33,'Maria Clara','F'),
    (34,'Rafael','M'),
    (35,'Maria Eduarda','F'),
    (36,'Guilherme','M'),
    (37,'Mariana','F'),
    (38,'Enzo','M'),
    (39,'Lara','F'),
    (40,'Murilo','M'),
    (41,'Beatriz','F'),
    (42,'Benício','M'),
    (43,'Antonella','F'),
    (44,'Gustavo','M'),
    (45,'Maria Júlia','F'),
    (46,'Isaac','M'),
    (47,'Emanuelly','F'),
    (48,'João Miguel','M'),
    (49,'Isadora','F'),
    (50,'Lucca','M'),
    (51,'Ana Clara','F'),
    (52,'Enzo Gabriel','M'),
    (53,'Melissa','F'),
    (54,'Pedro Henrique','M'),
    (55,'Ana Luiza','F'),
    (56,'Felipe','M'),
    (57,'Ana Júlia','F'),
    (58,'João Pedro','M'),
    (59,'Esther','F'),
    (60,'Pietro','M'),
    (61,'Lavínia','F'),
    (62,'Anthony','M'),
    (63,'Maitê','F'),
    (64,'Daniel','M'),
    (65,'Maria Cecília','F'),
    (66,'Bryan','M'),
    (67,'Maria Alice','F'),
    (68,'Davi Lucca','M'),
    (69,'Sarah','F'),
    (70,'Leonardo','M'),
    (71,'Elisa','F'),
    (72,'Vicente','M'),
    (73,'Liz','F'),
    (74,'Eduardo','M'),
    (75,'Yasmin','F'),
    (76,'Gael','M'),
    (77,'Isabelly','F'),
    (78,'Antônio','M'),
    (79,'Alícia','F'),
    (80,'Vitor','M'),
    (81,'Clara','F'),
    (82,'Noah','M'),
    (83,'Isis','F'),
    (84,'Caio','M'),
    (85,'Rebeca','F'),
    (86,'João','M'),
    (87,'Rafaela','F'),
    (88,'Emanuel','M'),
    (89,'Marina','F'),
    (90,'Cauã','M'),
    (91,'Ana Laura','F'),
    (92,'João Lucas','M'),
    (93,'Maria Helena','F'),
    (94,'Calebe','M'),
    (95,'Agatha','F'),
    (96,'Enrico','M'),
    (97,'Gabriela','F'),
    (98,'Vinícius','M'),
    (99,'Catarina','F'),
    (100,'Bento','M')
;